openapi: 3.1.0
info:
  title: Planning Activities API
  version: 0.1.0
  description: |
    REST-Schnittstelle für die Gantt-Aktivitäten der Order-Management-Anwendung.
    Alle Clients arbeiten gegen denselben Datenbestand. Validierungen für Orts-,
    Kapazitäts-, Arbeitszeit- und Qualifikationskonflikte werden serverseitig
    ausgeführt und können gezielt angefordert werden.
servers:
  - url: /api/v1
    description: Default Backend-URL (überschreibbar per API_CONFIG).
paths:
  /planning/base/templates:
    $ref: './planning/paths/base.yaml#/planning_base_templates'
  /planning/base/templates/{templateId}:
    $ref: './planning/paths/base.yaml#/planning_base_templates_templateId'
  /planning/base/templates/{templateId}/validities:
    $ref: './planning/paths/base.yaml#/planning_base_templates_templateId_validities'
  /planning/base/templates/{templateId}/validities/{validityId}:
    $ref: './planning/paths/base.yaml#/planning_base_templates_templateId_validities_validityId'
  /planning/base/templates:rollout:
    $ref: './planning/paths/base.yaml#/planning_base_templates_rollout'
  /planning/base/templates/events:
    $ref: './planning/paths/base.yaml#/planning_base_templates_events'
  /planning/operations/weeks:
    $ref: './planning/paths/operations.yaml#/planning_operations_weeks'
  /planning/operations/weeks/{weekInstanceId}:
    $ref: './planning/paths/operations.yaml#/planning_operations_weeks_weekInstanceId'
  /planning/stages/{stageId}:
    $ref: './planning/paths/stages.yaml#/planning_stages_stageId'
  /planning/stages/{stageId}/resources:
    $ref: './planning/paths/stages.yaml#/planning_stages_stageId_resources'
  /planning/stages/{stageId}/activities:
    $ref: './planning/paths/stages.yaml#/planning_stages_stageId_activities'
  /planning/stages/{stageId}/activities:validate:
    $ref: './planning/paths/stages.yaml#/planning_stages_stageId_activities_validate'
  /planning/stages/{stageId}/events:
    $ref: './planning/paths/stages.yaml#/planning_stages_stageId_events'
  /planning/master-data/personnel-service-pools:
    $ref: './planning/paths/master-data.yaml#/planning_master_data_personnel_service_pools'
  /planning/master-data/personnel-pools:
    $ref: './planning/paths/master-data.yaml#/planning_master_data_personnel_pools'
  /planning/master-data/vehicle-service-pools:
    $ref: './planning/paths/master-data.yaml#/planning_master_data_vehicle_service_pools'
  /planning/master-data/vehicle-pools:
    $ref: './planning/paths/master-data.yaml#/planning_master_data_vehicle_pools'
  /planning/master-data/vehicle-types:
    $ref: './planning/paths/master-data.yaml#/planning_master_data_vehicle_types'
  /planning/master-data/vehicle-compositions:
    $ref: './planning/paths/master-data.yaml#/planning_master_data_vehicle_compositions'
  /planning/topology/operational-points:
    $ref: './planning/paths/topology.yaml#/planning_topology_operational_points'
  /planning/topology/sections-of-line:
    $ref: './planning/paths/topology.yaml#/planning_topology_sections_of_line'
  /planning/topology/personnel-sites:
    $ref: './planning/paths/topology.yaml#/planning_topology_personnel_sites'
  /planning/topology/replacement-stops:
    $ref: './planning/paths/topology.yaml#/planning_topology_replacement_stops'
  /planning/topology/replacement-routes:
    $ref: './planning/paths/topology.yaml#/planning_topology_replacement_routes'
  /planning/topology/replacement-edges:
    $ref: './planning/paths/topology.yaml#/planning_topology_replacement_edges'
  /planning/topology/op-replacement-stop-links:
    $ref: './planning/paths/topology.yaml#/planning_topology_op_replacement_stop_links'
  /planning/topology/op-replacement-links:
    $ref: './planning/paths/topology.yaml#/planning_topology_op_replacement_links'
  /planning/topology/transfer-edges:
    $ref: './planning/paths/topology.yaml#/planning_topology_transfer_edges'
  /planning/topology/import:
    $ref: './planning/paths/topology.yaml#/planning_topology_import'
  /planning/topology/import/events:
    $ref: './planning/paths/topology.yaml#/planning_topology_import_events'
components:
  parameters:
    $ref: './planning/components/parameters.yaml#/parameters'
  schemas:
    $ref: './planning/components/schemas.yaml#/schemas'
